// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package words

import (
	"star2/api/words"
	userLogic "star2/internal/logic/users"
	wordsLogic "star2/internal/logic/words"
)

type ControllerV1 struct {
	usersLogic *userLogic.Users
	wordsLogic *wordsLogic.Words
}

func NewV1() words.IWordsV1 {
	return &ControllerV1{
		usersLogic: userLogic.New(),
		wordsLogic: wordsLogic.New(),
	}
}
