// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package account

import (
	"star2/api/account"
	userLogic "star2/internal/logic/users"
)

type ControllerV1 struct {
	users *userLogic.Users
}

func NewV1() account.IAccountV1 {
	return &ControllerV1{
		users: userLogic.New(),
	}
}
